
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

/** @typedef {"modern" | "baseline" | "default"} EmbeddedAddonVariant */

/**
 * @typedef {Object} EmbeddedAddonFile
 * @property {EmbeddedAddonVariant} variant
 * @property {string} filename
 * @property {number} size
 * @property {string=} filePath
 */

/**
 * @typedef {Object} EmbeddedAddonArchive
 * @property {"tar.gz"} format
 * @property {string} filename
 * @property {string} filePath
 */

/**
 * @typedef {Object} EmbeddedAddon
 * @property {string} platformTag
 * @property {string} version
 * @property {EmbeddedAddonFile[]} files
 * @property {EmbeddedAddonArchive=} archive
 */

import archivePath from "../native/embedded-addons.darwin-arm64.tar.gz" with { type: "file" };

export const embeddedAddon = {
	platformTag: "darwin-arm64",
	version: "17.0.1",
	archive: {
		format: "tar.gz",
		filename: "embedded-addons.darwin-arm64.tar.gz",
		filePath: archivePath,
	},
	files: [
		{ variant: "default", filename: "pi_natives.darwin-arm64.node", size: 135664256 },
	],
};
